{{- range $name, $binding := .Values.rbac.roleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
{{ include "chartpack.metadata" (dict "name" (printf "%s-%s" (include "chartpack.fullname" $) $name) "context" $ "extraAnnotations" $binding.annotations "extraLabels" $binding.labels) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ default "Role" $binding.roleRef.kind }}
  name: {{ printf "%s-%s" (include "chartpack.fullname" $) $binding.roleRef.name }}
subjects:
  {{- if $binding.subjects }}
  {{- toYaml $binding.subjects | nindent 2 }}
  {{- else }}
  - kind: ServiceAccount
    name: {{ include "chartpack.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
  {{- end }}
{{- end }}
