{{- range $name, $role := .Values.rbac.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
{{ include "universal-helm.metadata" (dict "name" (printf "%s-%s" (include "universal-helm.fullname" $) $name) "context" $ "extraAnnotations" $role.annotations "extraLabels" $role.labels) }}
rules:
  {{- toYaml $role.rules | nindent 2 }}
{{- end }}
