{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
{{ include "chartpack.metadata" (dict "name" (include "chartpack.serviceAccountName" .) "context" $ "extraAnnotations" .Values.serviceAccount.annotations "extraLabels" .Values.serviceAccount.labels) }}
{{- with .Values.serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: {{ . }}
{{- end }}
{{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
