apiVersion: v2
name: chartpack
description: A universal Helm chart for deploying any Kubernetes application workload
type: application
version: 1.0.2
appVersion: "1.0.0"
kubeVersion: ">=1.28.0-0"
keywords:
  - universal
  - deployment
  - statefulset
  - cronjob
  - daemonset
icon: https://raw.githubusercontent.com/cotzo/chartpack/main/images/logo.svg
home: https://github.com/cotzo/chartpack
sources:
  - https://github.com/cotzo/chartpack
maintainers:
  - name: cotzo
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/cotzo/chartpack/tree/main/docs
    - name: Source
      url: https://github.com/cotzo/chartpack
