{{- range $name, $config := .Values.externalSecrets }}
{{- if $config }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
{{ include "chartpack.metadata" (dict "name" (printf "%s-%s" (include "chartpack.fullname" $) $name) "context" $ "extraAnnotations" $config.annotations "extraLabels" $config.labels) }}
spec:
  {{- with $config.refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  secretStoreRef:
    name: {{ $config.secretStoreRef.name }}
    kind: {{ default "SecretStore" $config.secretStoreRef.kind }}
  target:
    name: {{ default (printf "%s-%s" (include "chartpack.fullname" $) $name) $config.target.name }}
    {{- with $config.target.creationPolicy }}
    creationPolicy: {{ . }}
    {{- end }}
    {{- with $config.target.deletionPolicy }}
    deletionPolicy: {{ . }}
    {{- end }}
    {{- with $config.target.template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with $config.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
