{{- if .Values.autoscaling.enabled }}
{{- if not (or (eq .Values.workloadType "CronJob") (eq .Values.workloadType "Job") (eq .Values.workloadType "DaemonSet")) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
{{ include "chartpack.metadata" (dict "context" $ "extraAnnotations" .Values.autoscaling.annotations "extraLabels" .Values.autoscaling.labels) }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.workloadType }}
    name: {{ include "chartpack.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{- with .Values.autoscaling.metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
