{{- if and .Values.autoscaling.keda.enabled (eq .Values.workloadType "Job") }}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
{{ include "chartpack.metadata" (dict "context" $ "extraAnnotations" .Values.autoscaling.keda.annotations "extraLabels" .Values.autoscaling.keda.labels) }}
spec:
  jobTargetRef:
    {{- with .Values.job.backoffLimit }}
    backoffLimit: {{ . }}
    {{- end }}
    {{- with .Values.job.activeDeadlineSeconds }}
    activeDeadlineSeconds: {{ . }}
    {{- end }}
    {{- with .Values.job.ttlSecondsAfterFinished }}
    ttlSecondsAfterFinished: {{ . }}
    {{- end }}
    {{- with .Values.job.completions }}
    completions: {{ . }}
    {{- end }}
    {{- with .Values.job.parallelism }}
    parallelism: {{ . }}
    {{- end }}
    {{- with .Values.job.completionMode }}
    completionMode: {{ . }}
    {{- end }}
    template:
      {{- include "chartpack.podTemplate" . | nindent 6 }}
  {{- with .Values.autoscaling.keda.pollingInterval }}
  pollingInterval: {{ . }}
  {{- end }}
  {{- with .Values.autoscaling.keda.minReplicaCount }}
  minReplicaCount: {{ . }}
  {{- end }}
  {{- with .Values.autoscaling.keda.maxReplicaCount }}
  maxReplicaCount: {{ . }}
  {{- end }}
  {{- with .Values.autoscaling.keda.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.autoscaling.keda.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.autoscaling.keda.scalingStrategy }}
  scalingStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  triggers:
    {{- toYaml .Values.autoscaling.keda.triggers | nindent 4 }}
{{- end }}
