{{/*
Return the CNPG Cluster resource name.
Usage: {{ include "chartpack.dependencies.postgres.clusterName" . }}
*/}}
{{- define "chartpack.dependencies.postgres.clusterName" -}}
{{- printf "%s-pg" (include "chartpack.fullname" .) -}}
{{- end }}

{{/*
Return the CNPG app secret name (auto-generated by CNPG operator).
Usage: {{ include "chartpack.dependencies.postgres.appSecretName" . }}
*/}}
{{- define "chartpack.dependencies.postgres.appSecretName" -}}
{{- printf "%s-pg-app" (include "chartpack.fullname" .) -}}
{{- end }}

{{/*
Return the credential secret name for ESO password mode.
Usage: {{ include "chartpack.dependencies.postgres.credentialSecretName" . }}
*/}}
{{- define "chartpack.dependencies.postgres.credentialSecretName" -}}
{{- printf "%s-pg-credentials" (include "chartpack.fullname" .) -}}
{{- end }}

{{/*
Return the CNPG image name.
Usage: {{ include "chartpack.dependencies.postgres.imageName" . }}
*/}}
{{- define "chartpack.dependencies.postgres.imageName" -}}
{{- $pg := .Values.dependencies.postgres -}}
{{- if $pg.imageName -}}
{{- $pg.imageName -}}
{{- else -}}
{{- printf "ghcr.io/cloudnative-pg/postgresql:%s" (default "16" $pg.version) -}}
{{- end -}}
{{- end }}

{{/*
Build the backup destination path from infraSettings or explicit override.
Usage: {{ include "chartpack.dependencies.postgres.destinationPath" . }}
*/}}
{{- define "chartpack.dependencies.postgres.destinationPath" -}}
{{- $pg := .Values.dependencies.postgres -}}
{{- $backup := $pg.backup -}}
{{- if $backup.destinationPath -}}
{{- $backup.destinationPath -}}
{{- else -}}
{{- $infra := default (dict) (default (dict) .Values.infraSettings).backups -}}
{{- $fullName := include "chartpack.fullname" . -}}
{{- $ns := .Release.Namespace -}}
{{- if eq $backup.type "s3" -}}
{{- $s3 := default (dict) $infra.s3 -}}
{{- $path := ternary (printf "%s/%s/%s" $s3.path $ns $fullName) (printf "%s/%s" $ns $fullName) (ne (default "" $s3.path) "") -}}
{{- printf "s3://%s/%s" $s3.bucket $path -}}
{{- else if eq $backup.type "azure" -}}
{{- $az := default (dict) $infra.azure -}}
{{- $path := ternary (printf "%s/%s/%s" $az.path $ns $fullName) (printf "%s/%s" $ns $fullName) (ne (default "" $az.path) "") -}}
{{- printf "https://%s.blob.core.windows.net/%s" $az.storageAccount $path -}}
{{- else if eq $backup.type "gcs" -}}
{{- $gcs := default (dict) $infra.gcs -}}
{{- $path := ternary (printf "%s/%s/%s" $gcs.path $ns $fullName) (printf "%s/%s" $ns $fullName) (ne (default "" $gcs.path) "") -}}
{{- printf "gs://%s/%s" $gcs.bucket $path -}}
{{- end -}}
{{- end -}}
{{- end }}
