{{/*
Return the CNPG Cluster resource name.
Usage: {{ include "chartpack.dependencies.postgres.clusterName" . }}
*/}}
{{- define "chartpack.dependencies.postgres.clusterName" -}}
{{- printf "%s-pg" (include "chartpack.fullname" .) -}}
{{- end }}

{{/*
Return the CNPG app secret name (auto-generated by CNPG operator).
Usage: {{ include "chartpack.dependencies.postgres.appSecretName" . }}
*/}}
{{- define "chartpack.dependencies.postgres.appSecretName" -}}
{{- printf "%s-pg-app" (include "chartpack.fullname" .) -}}
{{- end }}

{{/*
Return the credential secret name for ESO password mode.
Usage: {{ include "chartpack.dependencies.postgres.credentialSecretName" . }}
*/}}
{{- define "chartpack.dependencies.postgres.credentialSecretName" -}}
{{- printf "%s-pg-credentials" (include "chartpack.fullname" .) -}}
{{- end }}

{{/*
Return the CNPG image name.
Usage: {{ include "chartpack.dependencies.postgres.imageName" . }}
*/}}
{{- define "chartpack.dependencies.postgres.imageName" -}}
{{- $pg := .Values.dependencies.postgres -}}
{{- if $pg.imageName -}}
{{- $pg.imageName -}}
{{- else -}}
{{- printf "ghcr.io/cloudnative-pg/postgresql:%s" (default "16" $pg.version) -}}
{{- end -}}
{{- end }}

{{/*
Build a destination path from a backup type and infraSettings.
Usage: {{ include "chartpack.dependencies.postgres.buildDestinationPath" (dict "type" "s3" "context" $) }}
*/}}
{{- define "chartpack.dependencies.postgres.buildDestinationPath" -}}
{{- $infra := default (dict) (default (dict) .context.Values.infraSettings).backups -}}
{{- $fullName := include "chartpack.fullname" .context -}}
{{- $ns := .context.Release.Namespace -}}
{{- if eq .type "s3" -}}
{{- $s3 := default (dict) $infra.s3 -}}
{{- $path := ternary (printf "%s/%s/%s" $s3.path $ns $fullName) (printf "%s/%s" $ns $fullName) (ne (default "" $s3.path) "") -}}
{{- printf "s3://%s/%s" $s3.bucket $path -}}
{{- else if eq .type "azure" -}}
{{- $az := default (dict) $infra.azure -}}
{{- $path := ternary (printf "%s/%s/%s" $az.path $ns $fullName) (printf "%s/%s" $ns $fullName) (ne (default "" $az.path) "") -}}
{{- printf "https://%s.blob.core.windows.net/%s" $az.storageAccount $path -}}
{{- else if eq .type "gcs" -}}
{{- $gcs := default (dict) $infra.gcs -}}
{{- $path := ternary (printf "%s/%s/%s" $gcs.path $ns $fullName) (printf "%s/%s" $ns $fullName) (ne (default "" $gcs.path) "") -}}
{{- printf "gs://%s/%s" $gcs.bucket $path -}}
{{- end -}}
{{- end }}

{{/*
Build the backup destination path from infraSettings or explicit override.
Usage: {{ include "chartpack.dependencies.postgres.destinationPath" . }}
*/}}
{{- define "chartpack.dependencies.postgres.destinationPath" -}}
{{- $pg := .Values.dependencies.postgres -}}
{{- $backup := $pg.backup -}}
{{- if $backup.destinationPath -}}
{{- $backup.destinationPath -}}
{{- else -}}
{{- include "chartpack.dependencies.postgres.buildDestinationPath" (dict "type" $backup.type "context" .) -}}
{{- end -}}
{{- end }}

{{/*
Build the recovery destination path from infraSettings or explicit override.
Usage: {{ include "chartpack.dependencies.postgres.recoveryDestinationPath" . }}
*/}}
{{- define "chartpack.dependencies.postgres.recoveryDestinationPath" -}}
{{- $pg := .Values.dependencies.postgres -}}
{{- $recovery := $pg.recovery -}}
{{- if $recovery.destinationPath -}}
{{- $recovery.destinationPath -}}
{{- else -}}
{{- $recoveryType := default (default "s3" (default (dict) $pg.backup).type) $recovery.type -}}
{{- include "chartpack.dependencies.postgres.buildDestinationPath" (dict "type" $recoveryType "context" .) -}}
{{- end -}}
{{- end }}

{{/*
Render barmanObjectStore credentials block for a given backup type.
Usage: {{ include "chartpack.dependencies.postgres.barmanCredentials" (dict "type" "s3" "context" $) }}
*/}}
{{- define "chartpack.dependencies.postgres.barmanCredentials" -}}
{{- $infra := default (dict) (default (dict) .context.Values.infraSettings).backups -}}
{{- if eq .type "s3" -}}
{{- $s3 := default (dict) $infra.s3 -}}
{{- $s3creds := default (dict) $s3.credentials }}
{{- with $s3.endpoint }}
endpointURL: {{ . }}
{{- end }}
s3Credentials:
  accessKeyId:
    name: {{ $s3creds.secretName }}
    key: {{ default "ACCESS_KEY_ID" $s3creds.accessKeyId }}
  secretAccessKey:
    name: {{ $s3creds.secretName }}
    key: {{ default "ACCESS_SECRET_KEY" $s3creds.secretAccessKey }}
{{- else if eq .type "azure" -}}
{{- $az := default (dict) $infra.azure -}}
{{- $azcreds := default (dict) $az.credentials }}
azureCredentials:
  {{- with $azcreds.connectionString }}
  connectionString:
    name: {{ $azcreds.secretName }}
    key: {{ . }}
  {{- end }}
  {{- with $azcreds.storageAccount }}
  storageAccount:
    name: {{ $azcreds.secretName }}
    key: {{ . }}
  {{- end }}
  {{- with $azcreds.storageKey }}
  storageKey:
    name: {{ $azcreds.secretName }}
    key: {{ . }}
  {{- end }}
{{- else if eq .type "gcs" -}}
{{- $gcs := default (dict) $infra.gcs -}}
{{- $gcscreds := default (dict) $gcs.credentials }}
googleCredentials:
  applicationCredentials:
    name: {{ $gcscreds.secretName }}
    key: {{ default "gcsCredentials" $gcscreds.applicationCredentials }}
{{- end -}}
{{- end }}
