{{- if eq .Values.workloadType "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
{{ include "chartpack.metadata" (dict "context" $) }}
spec:
  {{- with .Values.daemonSet.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.daemonSet.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- with .Values.daemonSet.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chartpack.selectorLabels" . | nindent 6 }}
  template:
    {{- include "chartpack.podTemplate" . | nindent 4 }}
{{- end }}
