{{- include "universal-helm.validateWorkloadType" . -}}
{{- if eq .Values.workloadType "Deployment" }}
apiVersion: apps/v1
kind: Deployment
{{ include "universal-helm.metadata" (dict "context" $) }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.deployment.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- with .Values.deployment.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "universal-helm.selectorLabels" . | nindent 6 }}
  template:
    {{- include "universal-helm.podTemplate" . | nindent 4 }}
{{- end }}
