{{- include "chartpack.validate" . -}}
{{- if eq .Values.workloadType "Deployment" }}
apiVersion: apps/v1
kind: Deployment
{{ include "chartpack.metadata" (dict "context" $) }}
spec:
  {{- if not (or .Values.autoscaling.enabled .Values.keda.enabled) }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.deployment.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- with .Values.deployment.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chartpack.selectorLabels" . | nindent 6 }}
  template:
    {{- include "chartpack.podTemplate" . | nindent 4 }}
{{- end }}
