{{- if eq .Values.workloadType "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
{{ include "chartpack.metadata" (dict "context" $) }}
spec:
  {{- if not (or .Values.autoscaling.enabled .Values.keda.enabled) }}
  replicas: {{ .Values.statefulSet.replicaCount }}
  {{- end }}
  serviceName: {{ include "chartpack.networking.headlessServiceName" . }}
  {{- with .Values.statefulSet.podManagementPolicy }}
  podManagementPolicy: {{ . }}
  {{- end }}
  {{- with .Values.statefulSet.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.statefulSet.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- with .Values.statefulSet.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.statefulSet.ordinals }}
  ordinals:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.statefulSet.persistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chartpack.selectorLabels" . | nindent 6 }}
  template:
    {{- include "chartpack.podTemplate" . | nindent 4 }}
  {{- $vcts := include "chartpack.persistence.volumeClaimTemplates" . }}
  {{- if $vcts }}
  volumeClaimTemplates:
    {{- $vcts | nindent 4 }}
  {{- end }}
{{- end }}
